name: Publish Site
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "pyproject.toml"

      - name: Install Dependencies
        run: uv pip install -e .

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
